@startuml
!theme cerulean

participant AGR
participant CRO

AGR -> CRO: AGRPortfolioUpdate
AGR <-- CRO: HTTP OK

alt if CRO is operating in open mode
    AGR <- CRO: AGRPortfolioUpdateResponse Result=Accepted
    AGR --> CRO: HTTP OK
else
    alt if AGR is an authorized participant
        AGR <- CRO: AGRPortfolioUpdateResponse Result=Accepted
        AGR --> CRO: HTTP OK
    else
        AGR <- CRO: AGRPortfolioUpdateResponse Result=Rejected
        AGR --> CRO: HTTP OK
    end
end

@enduml