@startuml
!theme cerulean

participant DSO
participant CRO

DSO -> CRO: DSOPortfolioUpdate
DSO <-- CRO: HTTP OK

alt if CRO is operating in open mode
    DSO <- CRO: DSOPortfolioUpdateResponse Result=Accepted
    DSO --> CRO: HTTP OK
else
    alt if DSO is an authorized participant
        DSO <- CRO: DSOPortfolioUpdateResponse Result=Accepted
        DSO --> CRO: HTTP OK
    else
        DSO <- CRO: DSOPortfolioUpdateResponse Result=Rejected
        DSO --> CRO: HTTP OK
    end
end

@enduml