# Copyright Contributors to the Shapeshifter project
#
# SPDX-License-Identifier: Apache-2.0

name: docs-release

on:
  release:
    types:
      - published
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # checkout branch history required to update
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install Poetry and dependencies
        run: |
          pip install poetry
          poetry install --no-interaction
      - name: Configure fake git user to associate commits
        run: |
          git config --global user.name Docs deploy
          git config --global user.email docs-action@shapshifter
      - name: Set pdf subtitle to version
        run: |
          sed -i "s/cover_subtitle: \".*\"/cover_subtitle: \"Release: ${{ github.event.release.tag_name }}\"/" mkdocs.yml
          grep 'cover_subtitle:' mkdocs.yml
      - name: Push the verisioned documentation with alias latest
        run: poetry run mike deploy --push --update-aliases ${{ github.event.release.tag_name }} latest
        env:
          ENABLE_PDF_EXPORT: 1
      - name: Set latest as default (should only have te be run once)
        run: poetry run mike set-default --push latest
